<h2>Progress</h2><br />
<img src="img/progress_4.png" />

<br /><br />

<h2>Setup Stuff</h2>
<p>This is where you have to insert or edit the fields to fit the AAC system to what you want it to be like, below are a brief explanation of some of the things that are asked from you in this installation.</p>
<br />


<p><b>MySQL Details</b>:<br /><br />
<b>Security Options</b>:<br /><br />
<b>Spawn And Temple</b>:<br /><br />
<b>Other Server Details</b>:<br /><br />
<b>Common Fields</b>:<br /><br />
