<h2>Progress</h2><br />
<img src="img/progress_4.png" />

<br /><br />

<h2>Setup Stuff</h2>
<p>This is where you have to insert or edit the fields to fit the AAC system to what you want it to be like, below are a brief explanation of some of the things that are asked from you in this installation.</p>
<br />


<p><b>MySQL Details</b>:<br />
These are the settings to connect and use the database where accounts, players and other things are commonly stored for the otserver.<br /><br />
<b>Security Options</b>:<br />
Security is important for a website thats open to people, please consider these options with more consideration.<br /><br />
<b>Directories</b>:<br />
Just put the directory of your otservers data directory, such as /home/user/.otserv/data<br />
<b><u>DO NOT USE A TRAILING SLASH</u></b><br /><br />
<b>Other Server Details</b>:<br />
The details you provide here are simply just for the statistics page on your AAC site.<br /><br />
<b>Common Fields</b>:<br />
In your AAC, you can set how many min/max digits an account number can have, or how long a password must be. The lengths of some forms most used by visitors to the AAC.<br /><br />
<b>Modules</b>:<br />
These are pages in the installed AAC, you can enable or disable them whenever you like!<br /><br />
<b>Character settings</b>:<br />
This is the part where you set the start-values of the characters made by the AAC.<br /><br /></p>